### ISSUE TITLE
Can't get data 

### ISSUE THREAD

**Issue by LilaGuill** [rak-trzustki/busy-hours#3]
Hi,
Here is the code of my app :

app.get('/getPopularTime/:id', (req, res) => {
  console.log(req.params)
  busy_hours(req.params.id, API_KEY_PT).then(data => {
    console.log(data);
  });
});

My console.log displays data only one on 10 and also displays this error message:

(node:7072) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'status' of undefined
[0] (node:7072) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Can you help me ?
please,

**Comment by zmeeeeeva** [comment]
Could you provide examples of place ids causing the problem?

**Comment by LilaGuill** [comment]
for example this Id ChIJVUrgmz5u5kcRWPSN-T8a730

**Comment by zmeeeeeva** [comment]
This place simply doesn't have popular hours ;_;

```
{ name: 'Musée Grévin',
  formatted_address: '10 Boulevard Montmartre, 75009 Paris, France',
  location: { lat: 48.87183779999999, lng: 2.3422204 },
  status: 'error',
  message: 'Place has no popular hours' }
```
