### ISSUE TITLE
TypeError: Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by alexislouie** [rak-trzustki/busy-hours#7]
TypeError: Cannot read property 'status' of undefined
at busy_hours (......../node_modules/busy-hours/dist/index.js:1:1503)

My Code:
router.get('/:placeId', jsonParser, (req, res) => {
    const { placeId } = req.params;

    busy_hours(placeId, PLACES_API_KEY)
        .then(res => {
            if (res.status === 'ok' || res.status === 'error') {
                return res;
            } 
            else {
                throw Error(`Request rejected with status ${res.status}`);
            }
        })
        .then(data => res.status(200).json(data))
        .catch(console.error)
})

Seems to be triggering as soon as busy_hours is called. 
My code had been working last night but then I started getting this error for a couple places I tried looking up. Now it's happening every single time. 

Any help would be great. Thanks!

**Comment by mayurtikundi12** [comment]
did you get a solution @alouie1020

**Comment by mayurtikundi12** [comment]
if you see their code they are returning the error and it is not able to read the error but if you go into more depth it is working fine till midway we are getting all the data but there is some issue with data cleaning. can anyone from contributors look into it

**Comment by alexislouie** [comment]
@mayurtikundi12: I had reinstalled node modules and it started working again. Unfortunately I started getting the same error again a few weeks ago and I haven't been able to resolve it since.

**Comment by jsnx** [comment]
@alouie1020
@rak-trzustki 

has anyone found a solution. I do also face this issue with errorcode:

`TypeError: Cannot read property 'status' of undefined
    at busy_hours (/home/jsnx/sales_lead_crawler/node_modules/busy-hours/dist/index.js:1:1441)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)`

**Comment by jsnx** [comment]
I found a solution. You can read it here:
#8
